# Generated by Django 5.2.8 on 2025-11-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('preparation', models.TextField()),
                ('people', models.IntegerField(default=1)),
                ('onMenu', models.BooleanField(default=False)),
            ],
        ),
    ]
